name: yandex_map_parking_layer_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.3
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_gen_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/colors/
    - assets/

  fonts:
    - family: Santello
      fonts:
        - asset: assets/fonts/Santello-Regular.ttf

flutter_gen:
  output: lib/res/assets/
  style: camel-case
  colors:
    inputs:
      - assets/colors/colors.xml
  integrations:
    flutter_svg: true